### ISSUE TITLE
Output Tfs

### ISSUE THREAD

**Issue by BenjaminMorrell** [NeBula-Autonomy/LOCUS#2]
Often lidar odometry algorithms have an output tf that helps for visualization + comparisons. 

In our system, we removed tf publishing to be in the transform manager. 

Should we:
1. Put our own tf publishing (odom to base link) again?
2. Include transform manager (probably overkill)
3. Have a new package of a minimal transform manager? (Maybe also publishes static tfs for sensor calibrations)

**Comment by femust** [comment]
Merged in #43
