### ISSUE TITLE
Add tmuxp scripts for each dataset 

### ISSUE THREAD

**Issue by BenjaminMorrell** [NeBula-Autonomy/LOCUS#26]

**Comment by femust** [comment]
Something like [this](https://github.com/NeBula-Autonomy/LOCUS/tree/feature/costar_odometry_dataset/tmuxp_config/run_nebula_odometry_dataset) you want?

**Comment by BenjaminMorrell** [comment]
Yes! But let's simplify them for the release version to just be modification of this yaml:
https://github.com/NeBula-Autonomy/LOCUS/blob/main/tmuxp_config/nebula_odometry_datasets/E_Spot1_Valentine1.yaml

**Comment by femust** [comment]
@BenjaminMorrell yeap they are, though I removed the comments

**Comment by BenjaminMorrell** [comment]
Oh I see - sorry

**Comment by BenjaminMorrell** [comment]
Can you double-check the latest version of the script on `main` though - for instance, the rviz config is now named per robot and uses `$(echo $ROBOT_NAME)`

**Comment by femust** [comment]
Merged in #42
