### ISSUE TITLE
No map output!

### ISSUE THREAD

**Issue by qpc001** [NeBula-Autonomy/LOCUS#38]

**Comment by femust** [comment]
Hey @qpc001 can you provide more details?

**Comment by BenjaminMorrell** [comment]
A few notes:
1) the datasets don't start at the origin - so you might have to move the rviz around to find the map 
2) The dataset might take some time to start 
3) The map doesn't publish on every scan
4) The default settings have a sliding map - so only part of the map is published

**Comment by RobotGameFoundation** [comment]
I have the same issue with @qpc001.
In **run_locus.yaml** file 
change
`- rviz -d $(rospack find locus)/rviz/$ROBOT_NAME_locus.rviz `
to
`- rviz -d $(rospack find locus)/rviz/"$ROBOT_NAME"_locus.rviz `

You can see the map output

**Comment by BenjaminMorrell** [comment]
Thanks!

Updated in #40
