### ISSUE TITLE
Release GT Analysis tools 

### ISSUE THREAD

**Issue by BenjaminMorrell** [NeBula-Autonomy/LOCUS#5]
It might be useful to release a minimal version of GT Analysis (without computation and delay analysis) as just a wrapper around EVO to make it easy for people to analyze and compare datasets. It might be released with the datasets, or with LOCUS.

**Comment by femust** [comment]
@BenjaminMorrell  can you look over [here](https://github.com/NeBula-Autonomy/localization_analyzer/issues/1) and tell which one we do not need and which we want (just for confirmation), @yunzc  as well (for loop closures)

**Comment by femust** [comment]
ok it's [open here](https://github.com/NeBula-Autonomy/localization_analyzer)
